name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature-change-BG ]
  workflow_dispatch:

jobs:
  lint:
    name: Generating Lint Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Auto Increment Version
        run: |
          # Increment version code
          currentVersionCode=$(grep "versionCode" app/build.gradle | awk '{print $2}' | sed 's/[^0-9]*//g')
          newVersionCode=$((currentVersionCode + 1))
          sed -i "s/versionCode.*/versionCode $newVersionCode/" app/build.gradle
          
          # Increment version name
          currentVersionName=$(grep "versionName" app/build.gradle | awk '{print $2}' | sed 's/"//g')
          newVersionName="$((currentVersionName + 1))"
          sed -i "s/versionName.*/versionName \"$newVersionName\"/" app/build.gradle
          
      # For Building APK
      - name: Build debug APK
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0
        with:
          name: AuthLogin.apk
          path: app/build/outputs/apk/demo/paid/app-demo-paid.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
