name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature-change-BG ]
  workflow_dispatch:

jobs:
  lint:
    name: Generating Lint Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Bump Version Code
        run: |
            # Get the current version code
            currentVersionCode=$(grep "versionCode" app/build.gradle.kts | awk '{print $2}' | sed 's/[^0-9]*//g')
            
            # Increment the version code
            newVersionCode=$((currentVersionCode + 1))
            
            # Update the version code in build.gradle.kts
            sed -i "s/versionCode.*/versionCode $newVersionCode/" app/build.gradle.kts
            
            # Commit the changes
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add app/build.gradle
            git commit -m "Bump version code to $newVersionCode"
            git push

      # For Building APK
      - name: Build debug APK
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0
        with:
          name: AuthLogin.apk
          path: app/build/outputs/apk/demo/paid/app-demo-paid.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk

