name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature-change-BG ]
  workflow_dispatch:

jobs:
  lint:
    name: Generating Lint Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Bump Version Code
        run: |
          latest_version="$(git describe --match "[0-9]*\.[0-9]*\.[0-9]*"
              --abbrev=0 --tags)"
          change_to="versionName "\"$latest_version"\""
          sed -i "0,/versionName/{s/.*versionName.*/$change_to/}"
              buffer-android-app/build.gradle.kts
          git commit -m "Bump version release for $latest_version" -a

      # For Building APK
      - name: Build debug APK
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0
        with:
          name: AuthLogin.apk
          path: app/build/outputs/apk/demo/paid/app-demo-paid.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk

