name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature-change-BG ]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: set up JDK 1.8
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '1.8'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew build
#        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0
        with:
          name: AuthLogin.apk
          path: app/build/outputs/apk/debug/app-debug.apk